// src/lib/landing/icons.ts
//
// Icons a landing-page content file can ask for BY NAME.
//
// Content files are plain data — no imports, no JSX — so a new page is just
// a text file. `icon: 'megaphone'` resolves here. The name is typed, so a
// typo ('megafone') is a compile error, not a blank spot on a live page.
// Need one that is missing? Add a line below; every page can then use it.

import {
  BadgeCheck,
  BarChart3,
  Bell,
  Bot,
  Building2,
  CalendarCheck,
  Car,
  Check,
  Code2,
  CreditCard,
  Database,
  FileText,
  Filter,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  HeartPulse,
  Landmark,
  Layers,
  LayoutDashboard,
  Link2,
  Lock,
  Mail,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Percent,
  Phone,
  Plane,
  Plug,
  QrCode,
  Rocket,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Tag,
  Target,
  TrendingUp,
  Truck,
  UserCheck,
  Users,
  Wallet,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const ICONS = {
  'badge-check': BadgeCheck,
  'bar-chart': BarChart3,
  bell: Bell,
  bot: Bot,
  building: Building2,
  'calendar-check': CalendarCheck,
  car: Car,
  check: Check,
  code: Code2,
  'credit-card': CreditCard,
  database: Database,
  'file-text': FileText,
  filter: Filter,
  gift: Gift,
  globe: Globe,
  'graduation-cap': GraduationCap,
  handshake: Handshake,
  headphones: Headphones,
  'heart-pulse': HeartPulse,
  landmark: Landmark,
  layers: Layers,
  dashboard: LayoutDashboard,
  link: Link2,
  lock: Lock,
  mail: Mail,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  messages: MessagesSquare,
  percent: Percent,
  phone: Phone,
  plane: Plane,
  plug: Plug,
  'qr-code': QrCode,
  rocket: Rocket,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  tag: Tag,
  target: Target,
  'trending-up': TrendingUp,
  truck: Truck,
  'user-check': UserCheck,
  users: Users,
  wallet: Wallet,
  workflow: Workflow,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export function getIcon(name: IconName): LucideIcon {
  return ICONS[name]
}
