// src/lib/landing/registry.test.ts
//
// The quality gate for landing pages. It runs on every deploy, so a page
// with a mistake that would cost search traffic — a title Google truncates,
// a button that goes nowhere, a pasted video link that is not a video, a
// page nobody remembered to put in the sitemap — fails the build instead of
// shipping quietly.
//
// New landing page? You do not edit this file. Add the page to
// src/content/landing/index.ts and these checks pick it up.

import { describe, it, expect } from 'vitest'
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { LANDING_PAGES } from '@/content/landing'
import { parseVideoUrl } from '@/lib/video-embed'
import type { LandingContent } from './types'

const ROOT = process.cwd()
const APP_DIR = path.join(ROOT, 'src', 'app')

/** Top-level routes that already mean something else. A landing page may not take them. */
const TAKEN_SLUGS = new Set([
  'login', 'signup', 'forgot-password', 'callback', 'api', 'admin', 'tools', 'blog',
  'contact', 'privacy', 'terms', 'data-deletion', 'dashboard', 'inbox', 'contacts',
  'pipelines', 'broadcasts', 'automations', 'bookings', 'leads', 'widget', 'settings',
  'agents', 'journeys', 'analytics', 'health', 'billing', 'media', 'candidates', 'ads',
  'recent', 'integrations', 'sitemap.xml', 'robots.txt',
])

const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/
// A link must be a site path, an in-page anchor, or a full https URL.
const HREF = /^(\/[^\s]*|#[a-z0-9-]+|https:\/\/[^\s]+)$/

/** Every string found under `key` anywhere inside a content object. */
function collect(node: unknown, key: string, out: string[] = []): string[] {
  if (Array.isArray(node)) {
    node.forEach((n) => collect(n, key, out))
  } else if (node && typeof node === 'object') {
    for (const [k, v] of Object.entries(node)) {
      if (k === key && typeof v === 'string') out.push(v)
      else collect(v, key, out)
    }
  }
  return out
}

describe('landing page registry', () => {
  it('has at least one page', () => {
    expect(LANDING_PAGES.length).toBeGreaterThan(0)
  })

  it('has no duplicate slugs', () => {
    const slugs = LANDING_PAGES.map((p) => p.slug)
    expect(new Set(slugs).size).toBe(slugs.length)
  })

  it('lists every page that renders through the landing template', () => {
    // A page that exists but is not registered is live yet missing from the sitemap.
    const registered = new Set(LANDING_PAGES.map((p) => p.slug))
    const unregistered: string[] = []
    for (const entry of readdirSync(APP_DIR, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue
      const file = path.join(APP_DIR, entry.name, 'page.tsx')
      if (!existsSync(file)) continue
      if (readFileSync(file, 'utf8').includes('LandingPageView') && !registered.has(entry.name)) {
        unregistered.push(entry.name)
      }
    }
    expect(unregistered, 'add these to src/content/landing/index.ts').toEqual([])
  })
})

describe.each(LANDING_PAGES.map((p) => [p.slug, p] as [string, LandingContent]))(
  'landing page /%s',
  (_slug, page) => {
    it('has a clean URL slug that does not collide with an existing route', () => {
      expect(page.slug).toMatch(KEBAB)
      expect(TAKEN_SLUGS.has(page.slug), `"${page.slug}" is already used by the app`).toBe(false)
    })

    it('has a route file, so the sitemap never lists a 404', () => {
      expect(existsSync(path.join(APP_DIR, page.slug, 'page.tsx'))).toBe(true)
    })

    it('has a title that fits in a search result', () => {
      // The root layout appends " — AiSend" (9 chars); Google shows ~60.
      expect(page.seo.title.length).toBeGreaterThanOrEqual(10)
      expect(page.seo.title.length).toBeLessThanOrEqual(60)
    })

    it('has a description that fits in a search snippet', () => {
      expect(page.seo.description.length).toBeGreaterThanOrEqual(70)
      expect(page.seo.description.length).toBeLessThanOrEqual(160)
    })

    it('opens with exactly one hero (the page <h1>)', () => {
      expect(page.sections[0]?.type).toBe('hero')
      expect(page.sections.filter((s) => s.type === 'hero')).toHaveLength(1)
    })

    it('has unique, URL-safe section anchors', () => {
      const ids = page.sections.flatMap((s) => (s.id ? [s.id] : []))
      expect(new Set(ids).size).toBe(ids.length)
      for (const id of ids) expect(id).toMatch(KEBAB)
    })

    it('has dates the sitemap can use', () => {
      expect(page.published).toMatch(ISO_DATE)
      expect(page.updated).toMatch(ISO_DATE)
      expect(page.updated >= page.published).toBe(true)
    })

    it('has no button or link that goes nowhere', () => {
      const ids = new Set(page.sections.flatMap((s) => (s.id ? [s.id] : [])))
      for (const href of collect(page.sections, 'href')) {
        expect(href, `bad link "${href}"`).toMatch(HREF)
        if (href.startsWith('#')) {
          expect(ids.has(href.slice(1)), `"${href}" points at a section that does not exist`).toBe(true)
        }
      }
    })

    it('only uses https for pictures (or leaves them empty)', () => {
      const urls = [
        ...collect(page.sections, 'image'),
        ...collect(page.sections, 'avatar'),
        ...collect(page.sections, 'poster'),
        ...(page.seo.ogImage ? [page.seo.ogImage] : []),
      ]
      for (const url of urls) {
        if (url === '') continue
        expect(url, `picture link must be https: "${url}"`).toMatch(/^https:\/\/\S+$/)
      }
    })

    it('only has video links that actually play (or leaves them empty)', () => {
      for (const url of collect(page.sections, 'video')) {
        if (url === '') continue
        expect(
          parseVideoUrl(url).kind,
          `"${url}" is not a YouTube, Vimeo or .mp4 https link`,
        ).not.toBe('none')
      }
    })

    it('describes every picture for screen readers and search', () => {
      for (const section of page.sections) {
        if ('imageAlt' in section && 'image' in section) {
          expect(section.imageAlt?.trim().length, `${section.type} section needs imageAlt`).toBeGreaterThan(0)
        }
      }
    })
  },
)
